#!/usr/bin/env bash
# Check a maintenance patch against the path policy and open or update a pull request.
# This script runs with a GitHub write token: it must never run repository code.
# The agent job runs the validation command before the patch reaches this job.
set -euo pipefail

result_file="${RESULT_FILE:?RESULT_FILE is required}"
patch_file="${PATCH_FILE:?PATCH_FILE is required}"
branch_name="${BRANCH_PREFIX:-ai/maintenance}"
base_branch="${BASE_BRANCH:-main}"
allowed_path_regex="${ALLOWED_PATH_REGEX:-.}"
denied_path_regex="${DENIED_PATH_REGEX:-^\\.github/workflows/}"
commit_user_name="${COMMIT_USER_NAME:-agentic-bot}"
commit_user_email="${COMMIT_USER_EMAIL:-agentic-bot@users.noreply.github.com}"

if [[ ! -s "${patch_file}" ]]; then
  echo "Patch file is empty; nothing to publish"
  exit 0
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required" >&2
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "gh is required" >&2
  exit 1
fi

has_changes="$(jq -r '.has_changes // false' "${result_file}")"
if [[ "${has_changes}" != "true" ]]; then
  echo "Result artifact reports has_changes=false; skipping PR"
  exit 0
fi

title="$(jq -r '.title // empty' "${result_file}")"
body="$(jq -r '.body // empty' "${result_file}")"
draft="$(jq -r '.draft // true' "${result_file}")"
summary="$(jq -r '.summary // empty' "${result_file}")"

if [[ -z "${title}" || -z "${body}" ]]; then
  echo "Result artifact is missing title/body" >&2
  exit 1
fi

# The checkout does not persist credentials. Give the token only to the git
# commands that need it, through the environment (not argv or .git/config).
auth_header="AUTHORIZATION: basic $(printf 'x-access-token:%s' "${GH_TOKEN:?GH_TOKEN is required}" | base64 | tr -d '\n')"
git_auth() {
  GIT_CONFIG_COUNT=1 \
    GIT_CONFIG_KEY_0="http.${GITHUB_SERVER_URL:-https://github.com}/.extraheader" \
    GIT_CONFIG_VALUE_0="${auth_header}" \
    git "$@"
}

git_auth fetch --no-tags origin "${base_branch}"
# Refresh the remote-tracking ref so --force-with-lease compares with the real state.
git_auth fetch --no-tags origin "+refs/heads/${branch_name}:refs/remotes/origin/${branch_name}" 2>/dev/null || true

# Ensure a clean base before applying the patch.
git checkout -B "tmp-maintenance-base" "origin/${base_branch}"
git reset --hard "origin/${base_branch}"
git clean -fdx

if ! git apply --index --binary "${patch_file}"; then
  echo "Failed to apply maintenance patch" >&2
  exit 1
fi

changed_paths=()
while IFS= read -r path; do
  [[ -z "${path}" ]] && continue
  changed_paths+=("${path}")
done < <(git diff --cached --name-only)

if [[ "${#changed_paths[@]}" -eq 0 ]]; then
  echo "No files staged after applying patch"
  exit 0
fi

for path in "${changed_paths[@]}"; do
  if [[ ! "${path}" =~ ${allowed_path_regex} ]]; then
    echo "Changed path not allowed by ALLOWED_PATH_REGEX: ${path}" >&2
    exit 1
  fi
  if [[ "${path}" =~ ${denied_path_regex} ]]; then
    echo "Changed path denied by DENIED_PATH_REGEX: ${path}" >&2
    exit 1
  fi
done

git config user.name "${commit_user_name}"
git config user.email "${commit_user_email}"

git checkout -B "${branch_name}"
git commit -m "${title}"

git_auth push --force-with-lease origin "HEAD:refs/heads/${branch_name}"

pr_url="$(gh pr list --head "${branch_name}" --json url --jq '.[0].url // empty')"

full_body="$(cat <<EOF
${body}

---

### Agent summary

${summary}

_Generated by [mirego/agentic](https://github.com/mirego/agentic) Pi maintenance workflows._
EOF
)"

if [[ -n "${pr_url}" ]]; then
  gh pr edit "${pr_url}" --title "${title}" --body "${full_body}"
  echo "Updated pull request: ${pr_url}"
else
  create_args=(
    pr create
    --base "${base_branch}"
    --head "${branch_name}"
    --title "${title}"
    --body "${full_body}"
  )
  if [[ "${draft}" == "true" ]]; then
    create_args+=(--draft)
  fi

  # Labels are best-effort: missing labels should not fail the whole publish.
  while IFS= read -r label; do
    [[ -z "${label}" ]] && continue
    create_args+=(--label "${label}")
  done < <(jq -r '.labels // [] | .[]' "${result_file}")

  if ! gh "${create_args[@]}"; then
    echo "PR create with labels failed; retrying without labels" >&2
    create_args=(
      pr create
      --base "${base_branch}"
      --head "${branch_name}"
      --title "${title}"
      --body "${full_body}"
    )
    if [[ "${draft}" == "true" ]]; then
      create_args+=(--draft)
    fi
    gh "${create_args[@]}"
  fi
fi
