#!/usr/bin/env python3
"""Publish validated review findings as a GitHub pull request review."""

from __future__ import annotations

import json
import os
import sys
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any


API_VERSION = "2022-11-28"


def gh_request(method: str, url: str, token: str, payload: dict[str, Any] | None = None) -> Any:
    data = None
    headers = {
        "Accept": "application/vnd.github+json",
        "Authorization": f"Bearer {token}",
        "X-GitHub-Api-Version": API_VERSION,
        "User-Agent": "mirego-agentic-pi-review",
    }
    if payload is not None:
        data = json.dumps(payload).encode("utf-8")
        headers["Content-Type"] = "application/json"

    request = urllib.request.Request(url, data=data, headers=headers, method=method)
    try:
        with urllib.request.urlopen(request) as response:
            body = response.read().decode("utf-8")
            return json.loads(body) if body else None
    except urllib.error.HTTPError as error:
        details = error.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"GitHub API {method} {url} failed: {error.code} {details}") from error


def marker(profile: str) -> str:
    return f"<!-- agentic-pi-review:{profile} -->"


def finding_marker(finding_hash: str) -> str:
    return f"<!-- agentic-finding:{finding_hash} -->"


def format_finding(finding: dict[str, Any]) -> str:
    severity = finding["severity"].upper()
    confidence = finding.get("confidence", "medium")
    body = finding["body"].strip()
    title = finding["title"].strip()
    return (
        f"{finding_marker(finding['hash'])}\n"
        f"**{severity}** · confidence `{confidence}`\n\n"
        f"### {title}\n\n"
        f"{body}"
    )


def build_summary(
    profile: str,
    summary: str,
    inline_findings: list[dict[str, Any]],
    summary_findings: list[dict[str, Any]],
) -> str:
    lines = [
        marker(profile),
        f"## AI review · `{profile}`",
        "",
        summary.strip() or "Automated review completed.",
        "",
        f"- Inline findings: **{len(inline_findings)}**",
        f"- Summary-only findings: **{len(summary_findings)}**",
    ]

    if summary_findings:
        lines.extend(["", "### Findings without stable diff anchors", ""])
        for finding in summary_findings:
            path = finding["path"]
            start = finding.get("start_line")
            loc = f"{path}:{start}" if start else path
            lines.extend(
                [
                    f"- **{finding['severity'].upper()}** `{loc}` — {finding['title']}",
                    f"  {finding['body']}",
                    "",
                ]
            )

    if not inline_findings and not summary_findings:
        lines.extend(["", "_No material findings above the configured threshold._"])

    lines.extend(
        [
            "",
            "---",
            "_Generated by [mirego/agentic](https://github.com/mirego/agentic) Pi review workflows._",
        ]
    )
    return "\n".join(lines)


def existing_finding_hashes(token: str, repo: str, pr_number: str, profile: str) -> set[str]:
    """Best-effort dedupe using previous bot review bodies."""
    hashes: set[str] = set()
    url = f"https://api.github.com/repos/{repo}/pulls/{pr_number}/reviews?per_page=100"
    try:
        reviews = gh_request("GET", url, token)
    except RuntimeError as error:
        print(f"Warning: could not list previous reviews for dedupe: {error}", file=sys.stderr)
        return hashes

    prefix = marker(profile)
    for review in reviews or []:
        body = review.get("body") or ""
        if prefix not in body:
            continue
        for token_part in body.split("<!-- agentic-finding:")[1:]:
            value = token_part.split("-->", 1)[0].strip()
            if value:
                hashes.add(value)

    # Also inspect inline review comments.
    comments_url = f"https://api.github.com/repos/{repo}/pulls/{pr_number}/comments?per_page=100"
    try:
        comments = gh_request("GET", comments_url, token)
    except RuntimeError as error:
        print(f"Warning: could not list previous review comments for dedupe: {error}", file=sys.stderr)
        return hashes

    for comment in comments or []:
        body = comment.get("body") or ""
        if "<!-- agentic-finding:" not in body:
            continue
        value = body.split("<!-- agentic-finding:", 1)[1].split("-->", 1)[0].strip()
        if value:
            hashes.add(value)

    return hashes


def main() -> int:
    token = os.environ["GITHUB_TOKEN"]
    repo = os.environ["GITHUB_REPOSITORY"]
    pr_number = os.environ["PR_NUMBER"]
    head_sha = os.environ["HEAD_SHA"]
    profile = os.environ.get("PROFILE_NAME", "custom")
    validated_path = Path(os.environ["VALIDATED_FILE"])
    event = os.environ.get("REVIEW_EVENT", "COMMENT")

    payload = json.loads(validated_path.read_text(encoding="utf-8"))
    inline_findings = payload.get("inline_findings") or []
    summary_findings = payload.get("summary_findings") or []
    summary = payload.get("summary") or "Automated review completed."

    known = existing_finding_hashes(token, repo, pr_number, profile)
    if known:
        before = len(inline_findings) + len(summary_findings)
        inline_findings = [item for item in inline_findings if item.get("hash") not in known]
        summary_findings = [item for item in summary_findings if item.get("hash") not in known]
        after = len(inline_findings) + len(summary_findings)
        print(f"Deduped findings: {before} -> {after}")

    body = build_summary(profile, summary, inline_findings, summary_findings)

    comments = []
    for finding in inline_findings:
        comment: dict[str, Any] = {
            "path": finding["path"],
            "body": format_finding(finding),
            "side": finding.get("side") or "RIGHT",
        }
        start = finding.get("start_line")
        end = finding.get("end_line") or start
        if start is None:
            continue
        if end is not None and end != start:
            comment["start_line"] = start
            comment["start_side"] = comment["side"]
            comment["line"] = end
        else:
            comment["line"] = start
        comments.append(comment)

    review_payload = {
        "commit_id": head_sha,
        "body": body,
        "event": event,
        "comments": comments,
    }

    url = f"https://api.github.com/repos/{repo}/pulls/{pr_number}/reviews"
    result = gh_request("POST", url, token, review_payload)
    review_id = result.get("id") if isinstance(result, dict) else None
    print(f"Published review {review_id} with {len(comments)} inline comments")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as error:  # noqa: BLE001 - surface clean CI failure
        print(f"Failed to publish review: {error}", file=sys.stderr)
        sys.exit(1)
